[profiles.default]
    maxAPITries = 1
    output = "wholeResponse"
    apiTimeoutSecs = 20
    [profiles.default.accessKey]
        email = "person@example.com"
        id = "XXXXXXXXXXXXXX"
        secretAccessKey = "XXXXXXXXXXXXXXXXXXXXX"
        expiryDate = "2017-01-28T10:48:18Z"
